export { Home } from './Home'
export { Work } from './Work'
export { ProjectDetail } from './ProjectDetail'
export { Pricing } from './Pricing'
export { Quote } from './Quote'
export { About } from './About'
export { Contact } from './Contact'
export { NotFound } from './NotFound'